#!/bin/sh

set -e

#if test -f Makefile; then
#  make distclean
#fi
rm -rf config.guess config.log config.h config.h.in config.h.in~ install-sh compile \
    config.status config.sub depcomp ltmain.sh missing aclocal.m4 \
		m4/ltoptions.m4 m4/ltsugar.m4 m4/lt~obsolete.m4 m4/ltversion.m4 m4/libtool.m4 \
		autom4te.cache configure

touch NEWS README AUTHORS ChangeLog

#cat ./ac_utils.m4 > ./acinclude.m4
#cat ./ac_freezepython.m4 >> ./acinclude.m4
#cat ./ac_qt4.m4 >> ./acinclude.m4
#cat ./ac_pyqt.m4 >> ./acinclude.m4
#cat ./ac_numarray.m4 >> ./acinclude.m4
#cat ./ac_numeric.m4 >> ./acinclude.m4
#cat ./ac_numpy.m4 >> ./acinclude.m4
#cat ./ac_ctypes.m4 >> ./acinclude.m4
#cat ./ac_pyopengl.m4 >> ./acinclude.m4
#cat ./ac_pil.m4 >> ./acinclude.m4
#cat ./ac_cppunit.m4 >> ./acinclude.m4
#cat ./ac_pkg.m4 >> ./acinclude.m4

#aclocal
#autoheader
#libtoolize --force
#automake --foreign --add-missing --copy
#autoconf
autoreconf -ifv

