# $Id: Makefile 13189 2008-06-17 20:47:06Z brucesmith $

all : 
	@echo "Nothing is remade by default -- use one of the explicit make targets."

cleanpyc:
	find . -name \*.pyc -delete

clean: cleanpyc
	rm -f *~ *.o core
